<!DOCTYPE html>
<html lang="en" >

<head>
  <script type="text/javascript"></script>
  
  <meta charset="UTF-8">
  <title>MyFinance</title>
<!-- 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
  

<!--   <link rel='stylesheet prefetch' href='http://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css'> -->
  <link rel="stylesheet" type="text/css" href="../style/css/header.css">
  <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css'>  
  <link rel="stylesheet" type="text/css" href="../style/css/slick.css">

      <link rel="stylesheet" href="../style/css/style.css">

  
</head>

<body>
  <header class="banner" id="mainHeader" role="banner">

    <nav role="navigation">
        <div class="top-header">
            <div class="navBurger">
                <div class="burger"></div>
            </div>
        </div>
 
<!-- This part is the navigation generated by Wordpress himself.  -->
        <ul id="menu-vertical-menu" class="nav">
            <li><a href="../home/home.php">Home</a></li>
            <li><a href="#">Despesas</a></li>
            <li><a href="../Renda/renda.php">Rendas</a></li>
            <li><a href="../metas/metas.php">Metas</a></li>
            <li><a href="#">Relatórios</a></li>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Meus dados</a></li>
            <li><a href="../index.html">Sair</a></li>

    </ul>
    </nav>
    
</header>
